// Centralized currency options list (ISO 4217 where applicable)
// Labels include name, code, and symbol for clarity
export const currencyOptions = [
  // Africa
  { value: 'DZD', label: 'Algerian Dinar (DZD) - د.ج' },
  { value: 'AOA', label: 'Angolan Kwanza (AOA) - Kz' },
  { value: 'BWP', label: 'Botswana Pula (BWP) - P' },
  { value: 'BIF', label: 'Burundian Franc (BIF) - Fr' },
  { value: 'XOF', label: 'CFA Franc (West Africa) (XOF) - CFA' },
  { value: 'XAF', label: 'CFA Franc (Central Africa) (XAF) - FCFA' },
  { value: 'KMF', label: 'Comoros Franc (KMF) - Fr' },
  { value: 'CDF', label: 'Congolese Franc (CDF) - Fr' },
  { value: 'DJF', label: 'Djiboutian Franc (DJF) - Fdj' },
  { value: 'EGP', label: 'Egyptian Pound (EGP) - ج.م' },
  { value: 'ERN', label: 'Eritrean Nakfa (ERN) - Nkf' },
  { value: 'ETB', label: 'Ethiopian Birr (ETB) - Br' },
  { value: 'GMD', label: 'Gambian Dalasi (GMD) - D' },
  { value: 'GHS', label: 'Ghanaian Cedi (GHS) - ₵' },
  { value: 'GNF', label: 'Guinean Franc (GNF) - Fr' },
  { value: 'KES', label: 'Kenyan Shilling (KES) - KSh' },
  { value: 'LSL', label: 'Lesotho Loti (LSL) - L' },
  { value: 'LRD', label: 'Liberian Dollar (LRD) - $' },
  { value: 'LYD', label: 'Libyan Dinar (LYD) - د.ل' },
  { value: 'MWK', label: 'Malawian Kwacha (MWK) - MK' },
  { value: 'MUR', label: 'Mauritian Rupee (MUR) - ₨' },
  { value: 'MAD', label: 'Moroccan Dirham (MAD) - د.م.' },
  { value: 'MZN', label: 'Mozambican Metical (MZN) - MT' },
  { value: 'NAD', label: 'Namibian Dollar (NAD) - N$' },
  { value: 'NGN', label: 'Nigerian Naira (NGN) - ₦' },
  { value: 'RWF', label: 'Rwandan Franc (RWF) - Fr' },
  { value: 'STN', label: 'São Tomé and Príncipe Dobra (STN) - Db' },
  { value: 'SCR', label: 'Seychellois Rupee (SCR) - ₨' },
  { value: 'SLL', label: 'Sierra Leonean Leone (SLL) - Le' },
  { value: 'SOS', label: 'Somali Shilling (SOS) - Sh' },
  { value: 'ZAR', label: 'South African Rand (ZAR) - R' },
  { value: 'SSP', label: 'South Sudanese Pound (SSP) - £' },
  { value: 'SDG', label: 'Sudanese Pound (SDG) - ج.س' },
  { value: 'TZS', label: 'Tanzanian Shilling (TZS) - TSh' },
  { value: 'TND', label: 'Tunisian Dinar (TND) - د.ت' },
  { value: 'UGX', label: 'Ugandan Shilling (UGX) - Sh' },
  { value: 'ZMW', label: 'Zambian Kwacha (ZMW) - K' },
  { value: 'ZWL', label: 'Zimbabwean Dollar (ZWL) - Z$' },

  // Americas
  { value: 'ARS', label: 'Argentine Peso (ARS) - $' },
  { value: 'BSD', label: 'Bahamian Dollar (BSD) - $' },
  { value: 'BBD', label: 'Barbadian Dollar (BBD) - Bds$' },
  { value: 'BZD', label: 'Belize Dollar (BZD) - BZ$' },
  { value: 'BOB', label: 'Bolivian Boliviano (BOB) - Bs.' },
  { value: 'BRL', label: 'Brazilian Real (BRL) - R$' },
  { value: 'CAD', label: 'Canadian Dollar (CAD) - C$' },
  { value: 'CLP', label: 'Chilean Peso (CLP) - $' },
  { value: 'COP', label: 'Colombian Peso (COP) - $' },
  { value: 'CRC', label: 'Costa Rican Colón (CRC) - ₡' },
  { value: 'CUP', label: 'Cuban Peso (CUP) - ₱' },
  { value: 'DOP', label: 'Dominican Peso (DOP) - RD$' },
  { value: 'XCD', label: 'East Caribbean Dollar (XCD) - EC$' },
  { value: 'USD', label: 'United States Dollar (USD) - $' },
  { value: 'SVC', label: 'El Salvadorian Colón (SVC) - ₡' },
  { value: 'GTQ', label: 'Guatemalan Quetzal (GTQ) - Q' },
  { value: 'HTG', label: 'Haitian Gourde (HTG) - G' },
  { value: 'HNL', label: 'Honduran Lempira (HNL) - L' },
  { value: 'JMD', label: 'Jamaican Dollar (JMD) - J$' },
  { value: 'MXN', label: 'Mexican Peso (MXN) - $' },
  { value: 'NIO', label: 'Nicaraguan Córdoba (NIO) - C$' },
  { value: 'PAB', label: 'Panamanian Balboa (PAB) - B/.' },
  { value: 'PYG', label: 'Paraguayan Guarani (PYG) - ₲' },
  { value: 'PEN', label: 'Peruvian Sol (PEN) - S/' },
  { value: 'SRD', label: 'Surinamese Dollar (SRD) - $' },
  { value: 'TTD', label: 'Trinidad and Tobago Dollar (TTD) - TT$' },
  { value: 'UYU', label: 'Uruguayan Peso (UYU) - $U' },
  { value: 'VES', label: 'Venezuelan Bolívar (VES) - Bs.S' },

  // Europe (current)
  { value: 'ALL', label: 'Albanian Lek (ALL) - L' },
  { value: 'EUR', label: 'Euro (EUR) - €' },
  { value: 'AMD', label: 'Armenian Dram (AMD) - Դ' },
  { value: 'AZN', label: 'Azerbaijani Manat (AZN) - ₼' },
  { value: 'BYN', label: 'Belarusian Ruble (BYN) - Br' },
  { value: 'BAM', label: 'Bosnia and Herzegovina Mark (BAM) - KM' },
  { value: 'BGN', label: 'Bulgarian Lev (BGN) - лв' },
  { value: 'CZK', label: 'Czech Koruna (CZK) - Kč' },
  { value: 'DKK', label: 'Danish Krone (DKK) - kr' },
  { value: 'GEL', label: 'Georgian Lari (GEL) - ₾' },
  { value: 'GIP', label: 'Gibraltar Pound (GIP) - £' },
  { value: 'HUF', label: 'Hungarian Forint (HUF) - Ft' },
  { value: 'ISK', label: 'Icelandic Króna (ISK) - kr' },
  { value: 'KZT', label: 'Kazakhstani Tenge (KZT) - ₸' },
  { value: 'MKD', label: 'Macedonian Denar (MKD) - ден' },
  { value: 'MDL', label: 'Moldovan Leu (MDL) - leu' },
  { value: 'NOK', label: 'Norwegian Krone (NOK) - kr' },
  { value: 'PLN', label: 'Polish Zloty (PLN) - zł' },
  { value: 'RON', label: 'Romanian Leu (RON) - lei' },
  { value: 'RUB', label: 'Russian Ruble (RUB) - ₽' },
  { value: 'RSD', label: 'Serbian Dinar (RSD) - дин' },
  { value: 'SEK', label: 'Swedish Krona (SEK) - kr' },
  { value: 'CHF', label: 'Swiss Franc (CHF) - Fr.' },
  { value: 'TRY', label: 'Turkish Lira (TRY) - ₺' },
  { value: 'UAH', label: 'Ukrainian Hryvnia (UAH) - ₴' },
  { value: 'GBP', label: 'United Kingdom Pound (GBP) - £' },

  // Asia
  { value: 'AFN', label: 'Afghan Afghani (AFN) - ؋' },
  { value: 'BHD', label: 'Bahraini Dinar (BHD) - د.ب' },
  { value: 'BDT', label: 'Bangladeshi Taka (BDT) - ৳' },
  { value: 'BTN', label: 'Bhutanese Ngultrum (BTN) - Nu.' },
  { value: 'BND', label: 'Brunei Dollar (BND) - B$' },
  { value: 'KHR', label: 'Cambodian Riel (KHR) - ៛' },
  { value: 'CNY', label: 'Chinese Yuan (CNY) - ¥' },
  { value: 'HKD', label: 'Hong Kong Dollar (HKD) - $' },
  { value: 'INR', label: 'Indian Rupee (INR) - ₹' },
  { value: 'IDR', label: 'Indonesian Rupiah (IDR) - Rp' },
  { value: 'IRR', label: 'Iranian Rial (IRR) - ﷼' },
  { value: 'IQD', label: 'Iraqi Dinar (IQD) - د.ع' },
  { value: 'ILS', label: 'Israeli New Shekel (ILS) - ₪' },
  { value: 'JPY', label: 'Japanese Yen (JPY) - ¥' },
  { value: 'JOD', label: 'Jordanian Dinar (JOD) - د.ا' },
  { value: 'KWD', label: 'Kuwaiti Dinar (KWD) - د.ك' },
  { value: 'KGS', label: 'Kyrgyzstani Som (KGS) - с' },
  { value: 'LAK', label: 'Laotian Kip (LAK) - ₭' },
  { value: 'LBP', label: 'Lebanese Pound (LBP) - ل.ل' },
  { value: 'MYR', label: 'Malaysian Ringgit (MYR) - RM' },
  { value: 'MVR', label: 'Maldivian Rufiyaa (MVR) - Rf' },
  { value: 'MNT', label: 'Mongolian Tugrik (MNT) - ₮' },
  { value: 'NPR', label: 'Nepalese Rupee (NPR) - ₨' },
  { value: 'KPW', label: 'North Korean Won (KPW) - ₩' },
  { value: 'OMR', label: 'Omani Rial (OMR) - ر.ع.' },
  { value: 'PKR', label: 'Pakistani Rupee (PKR) - ₨' },
  { value: 'PHP', label: 'Philippine Peso (PHP) - ₱' },
  { value: 'QAR', label: 'Qatari Rial (QAR) - ر.ق' },
  { value: 'SAR', label: 'Saudi Riyal (SAR) - ر.س' },
  { value: 'SGD', label: 'Singapore Dollar (SGD) - S$' },
  { value: 'LKR', label: 'Sri Lankan Rupee (LKR) - ₨' },
  { value: 'SYP', label: 'Syrian Pound (SYP) - ل.س' },
  { value: 'TJS', label: 'Tajikistani Somoni (TJS) - ЅМ' },
  { value: 'TMT', label: 'Turkmenistan Manat (TMT) - m' },
  { value: 'AED', label: 'United Arab Emirates Dirham (AED) - د.إ' },
  { value: 'UZS', label: 'Uzbekistani Som (UZS) - с' },
  { value: 'VND', label: 'Vietnamese Dong (VND) - ₫' },
  { value: 'YER', label: 'Yemeni Rial (YER) - ر.ي' },
  { value: 'THB', label: 'Thai Baht (THB) - ฿' },
  { value: 'TWD', label: 'New Taiwan Dollar (TWD) - NT$' },
  { value: 'KRW', label: 'South Korean Won (KRW) - ₩' },
];

export default currencyOptions;
